import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import styles from "../styles/Home.module.css";

export default function Home() {
  return (
    /*     <>
      <Link href="/walcart/walCart">Walcart</Link> || <Link href="/flexbox/flexBox">Flexbox</Link>
      <h1 className="text-3xl font-bold underline">Hello world!</h1>

      <div className={styles.header_main}>
        <div className={styles.top}>t</div>
        <div className={styles.middle}>
          <input type="text" placeholder="dsad" />
        </div>
        <div className={styles.bottom}>b</div>
      </div>
    </>
 */
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <span>Wa</span> in Next.js!
        </h1>

        <p className={styles.description}>
          Get started by editing{" "}
          <code className={styles.code}>pages/index.js</code>
        </p>

        <div className={styles.grid}>
          <a href="http://vuecore.reviewsheeter.com/" className={styles.card}>
            <h2>Walcart UI &rarr;</h2>
            <p>Please click here to see this UI only Using React Js</p>
          </a>

          <a href="#" className={styles.card}>
            <h2>Application &rarr;</h2>
            <p>Redux and GraphQL Simple Appication</p>
          </a>

          <a href="/flexbox/flexBox" className={styles.card}>
            <h2>Card Design &rarr;</h2>
            <p>React Component Using Flexbox</p>
          </a>

          {/* <a
            href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
          >
            <h2>Deploy &rarr;</h2>
            <p>
              Instantly deploy your Next.js site to a public URL with Vercel.
            </p>
          </a> */}
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
}
